module.exports = [
    "AT&T Stadium",
    "MetLife Stadium",
    "SoFi Stadium",
    "Lambeau Field",
    "Mercedes-Benz Stadium",
    "Arrowhead Stadium",
    "Gillette Stadium",
    "Soldier Field",
    "CenturyLink Field",
    "FedExField",
    "Hard Rock Stadium",
    "Levi's Stadium",
    "Nissan Stadium",
    "Ford Field",
    "M&T Bank Stadium",
    "Heinz Field",
    "U.S. Bank Stadium",
    "Lucas Oil Stadium",
    "Raymond James Stadium",
    "Bank of America Stadium",
    "Lincoln Financial Field",
    "Paul Brown Stadium",
    "FirstEnergy Stadium",
    "Empower Field at Mile High",
    "NRG Stadium",
    "State Farm Stadium",
    "TIAA Bank Field",
    "Arrowhead Stadium",
    "Allegiant Stadium",
    "Mercedes-Benz Superdome",
    "AT&T Park",
    "Globe Life Field",
    "Dodger Stadium",
    "Wrigley Field",
    "Yankee Stadium",
    "Fenway Park",
    "Citi Field",
    "Petco Park",
    "Coors Field",
    "Oracle Park",
    "Target Field",
    "Tropicana Field",
    "Chase Field",
    "Miller Park",
    "Kauffman Stadium",
    "Oriole Park at Camden Yards",
    "PNC Park",
    "Great American Ball Park",
    "Guaranteed Rate Field",
    "Progressive Field"
  ];
