module.exports = [
    "Adelaide Oval", "Arnos Vale Stadium", "Barabati Stadium", "Basin Reserve", 
    "Bay Oval", "Beausejour Stadium", "Bellerive Oval", "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
    "Brabourne Stadium", "Brisbane Cricket Ground", "Buffalo Park", "Bulawayo Athletic Club",
    "Carisbrook", "Castle Avenue", "Central Broward Regional Park", "Civil Service Cricket Club",
    "Colombo Cricket Club Ground", "County Ground, Bristol", "County Ground, Hove", "County Ground, Taunton",
    "Darren Sammy National Cricket Stadium", "De Beers Diamond Oval", "Desert Springs Cricket Ground", "Docklands Stadium",
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium", "Dr. DY Patil Sports Academy", "Dunedin", "Edgbaston",
    "Eden Gardens", "Eden Park", "Gaddafi Stadium", "Galle International Stadium", "Ganguly Park", "Grace Road",
    "Greenfield International Stadium", "Green Park Stadium", "Gujarat Stadium", "Gymkhana Club Ground", 
    "Hagley Oval", "Harare Sports Club", "Headingley", "Holkar Cricket Stadium", "HPCA Stadium", "ICC Academy Ground",
    "India Cement Ltd Ground", "Indian Oil Corporation Ground", "Indira Priyadarshini Stadium", "Iqbal Stadium",
    "Jadavpur University Campus Ground", "Jawaharlal Nehru Stadium", "Jubilee Park", "JSCA International Stadium Complex",
    "Kardinia Park", "Keenan Stadium", "Kensington Oval", "Kingsmead", "Klerksdorp Recreation Ground", "Kolkata Stadium",
    "Lal Bahadur Shastri Stadium", "Lancashire County Cricket Club", "Lavington Sports Ground", "Lord's", 
    "M Chinnaswamy Stadium", "M. A. Chidambaram Stadium", "M. A. Aziz Stadium", "Madhavrao Scindia Cricket Ground",
    "Maharashtra Cricket Association Stadium", "Manuka Oval", "Marrara Cricket Ground", "McLean Park", 
    "Melbourne Cricket Ground", "Moin-ul-Haq Stadium", "Mombasa Sports Club Ground", "Moses Mabhida Stadium", 
    "Motera Stadium", "Multan Cricket Stadium", "Narendra Modi Stadium", "National Stadium, Karachi", 
    "New Wanderers Stadium", "Newlands", "North Sydney Oval", "Old Trafford", "P Sara Oval", "Pallekele International Cricket Stadium", 
    "Perth Stadium", "Port Elizabeth", "Providence Stadium", "Punjab Cricket Association IS Bindra Stadium", 
    "Queen's Park Oval", "R. Premadasa Stadium", "Rajiv Gandhi International Cricket Stadium", "Ranchi", 
    "Rawalpindi Cricket Stadium", "Sabina Park", "Sawai Mansingh Stadium", "SCG", "Sharjah Cricket Stadium",
    "Sheikh Zayed Cricket Stadium", "Sher-e-Bangla National Cricket Stadium", "Sree Kanteerava Stadium", 
    "St George's Park", "Supersport Park", "Sydney Cricket Ground", "Vidarbha Cricket Association Stadium", 
    "WACA Ground", "Warner Park", "Westpac Stadium"
];
